name: POC Self-hosted Issue Trigger (benign)
on:
  issues:
    types: [opened]

permissions:
  issues: write

jobs:
  demo:
    runs-on: self-hosted
    steps:
      - name: Show test marker
        run: |
          echo "POC-BENIGN-MARKER-$(date +%s)-$(hostname)"
